openrouter:
  api_key: ""
  embedding_url: "http://host.docker.internal:1234/v1/embeddings"
  model: "text-embedding-nomic-embed-text-v1.5@q8_0"
chroma:
  persist_directory: "/workspace/RAG/chroma_db"
